### ISSUE TITLE
Artillery not running

### ISSUE THREAD

**Issue by DrDinosaur** [trustedsec/artillery#25]
I get the output:

Checking Artillery...                             Process dead but pidfile exists

when I run "service artillery status." I have rebooted the system and restarted artillery.

**Comment by whoamiTM** [comment]
I have the same issue, but turning off email doesn't work.
$ sudo nohup python /var/artillery/artillery.py
$ sudo tail -f nohup.out

Said I needed to mkdir /var/artillery/database
$ mkdir /var/artillery/database
$ touch /var/artillery/database/temp.database
$ service artillery restart

All is good now...
