### ISSUE TITLE
Fatal Python error: PyImport_GetModuleDict: no module dictionary!

### ISSUE THREAD

**Issue by merollacoaster** [trustedsec/artillery#59]
Installing on AilenVault OSSIM.  I have 5 others running flawlessly, just on this 1, I cannot get artillery to run ...

 ./artillery.py
[*] 2015-03-17 00:37:07: Artillery has started successfully.
[*] Console logging enabled.

Has not found configuration file for ftp. Ftp monitor now stops.
General exception: zero length field name in format
Fatal Python error: PyImport_GetModuleDict: no module dictionary!
Aborted

**Comment by trustedsec** [comment]
Unable to reproduce this - will take a look for next release.
