### ISSUE TITLE
Setup Installer fails on Windows 7 64 bit. 

### ISSUE THREAD

**Issue by Kashman24** [trustedsec/artillery#60]
When I run Python shell script using IDLE, I get the following errors on Windows 7 64 bit. I have removed the "C:\program files\artillery" folder before running it and still get the error. Scripts run as local admin.

Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Welcome to the Artillery installer. Artillery is a honeypot, file monitoring, and overall security tool used to protect your nix systems.

Written by: Dave Kennedy (ReL1K)

Do you want to install Artillery and have it automatically run when you restart [y/n]: y

Traceback (most recent call last):
  File "C:\Python27\artillery-master\setup.py", line 61, in <module>
    os.makedirs(program_files + "\\Artillery\\logs")
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Program Files\\Artillery\\logs'
>>>

**Comment by smathermather** [comment]
Running into the same issue on Windows 8 64-bit.

**Comment by trustedsec** [comment]
Still working on full Windows integration, should be in next release.

**Comment by Kashman24** [comment]
We are looking for Windows 8 64-bit compatibility. When will the next version be released?
