### ISSUE TITLE
Problem with setup.py in Kali 2.0

### ISSUE THREAD

**Issue by oncee** [trustedsec/artillery#63]
root@kali:~/artillery# ./setup.py 
Traceback (most recent call last):
  File "./setup.py", line 7, in <module>
    from src.core import *
  File "/root/artillery/src/core.py", line 503
    return
         ^
IndentationError: unindent does not match any outer indentation level

**Comment by ernests** [comment]
Same error on Ubuntu

**Comment by Lazl0** [comment]
Also in Debian as well as Kali, and Fedora.

**Comment by Lazl0** [comment]
Somebody in there IDE did not have there tab set up properly, easy mistake.
At line 494 in core.py where this starts go to line 502 and 503 delete all the spaces then click the space bar four times in nano or vi. This will fix it.
     f = urllib2.urlopen(req).readlines()
  except urllib2.HTTPError, err:
      if err.code == '404':
          # Error 404, page not found!
          write_log("HTTPError: Error 404, URL {} not found.".format(url))
      return
  except urllib2.URLError, err:
        # Name or service not found known, DNS unreachable, try again later!
    write_log("Received URL Error, Reason: {}".format(err.reason))
    return

**Comment by oncee** [comment]
This fix does not work for me.

**Comment by oncee** [comment]
Fixed Indentation Error and submitted pull request.
