### ISSUE TITLE
Error when launching setup.py

### ISSUE THREAD

**Issue by stanou63** [trustedsec/artillery#66]
Hello, i encounter an error when i was launching setup.py with python 2.7.9 and python 3.4.2.

./setup.py
Traceback (most recent call last):
  File "./setup.py, line 7, in <module>
    from src.come import *
  File "/opt/artillery/src/core.py", line 503
    return
           ^

IndentationError: unindent does not match any outer indentation level

Thanks for your help
Stan !

**Comment by JexDev** [comment]
same here. python 2.7.6

**Comment by oncee** [comment]
I've fixed this issue and have submitted a pull request: https://github.com/trustedsec/artillery/pull/65

**Comment by trustedsec** [comment]
Thanks !
