### ISSUE TITLE
Error with setup.py

### ISSUE THREAD

**Issue by sirulian** [trustedsec/artillery#68]
hi! using this on kali 2.0, i'm getting this error when running the setup.py:

python setup.py
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import py2exe, sys, paramiko, ecdsa, ssl, ctypes, _ctypes, _thread
ImportError: No module named py2exe

I haven't been able to figure it out. Any help?

**Comment by the-c0d3r** [comment]
It is not program's fault. The error message is pretty much self explantory. It means py2exe is not installed. You just have to install it. `pip install py2exe`
