### ISSUE TITLE
artillery has detected a change - exclude wonkiness?

### ISSUE THREAD

**Issue by myobfee** [trustedsec/artillery#69]
no matter what I try, artillery seems to be disliking my entry in the Exclude statement for a directory.

Trying to get it to ignore the webmin status directory with this:

EXCLUDE="/etc/webmin/system-status/"

restart artillery and it persists... is it not smart enough to recurse?

**Comment by trustedsec** [comment]
Artillery has moved over to github.com/binarydefense/artillery - I'll look at adding this.
