### ISSUE TITLE
syslog Size

### ISSUE THREAD

**Issue by kevp75** [trustedsec/artillery#70]
Is there a way to limit the size of the log?  Or change what artillery logs to, and then limit it's size?

**Comment by kevp75** [comment]
And is there a way to configure CIDR address for the whitelist?

**Comment by trustedsec** [comment]
CIDR addresses are already supported on whitelist =) on the size of the log, not currently. Artillery has moved over to github.com/binarydefense/artillery - I'll look at adding this.
